/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sola_sky_zyt_linktolove_myjni_Calculate */

#ifndef _Included_com_sola_sky_zyt_linktolove_myjni_Calculate
#define _Included_com_sola_sky_zyt_linktolove_myjni_Calculate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sola_sky_zyt_linktolove_myjni_Calculate
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_sola_1sky_zyt_linktolove_myjni_Calculate_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
